Fix ClassLoader caching to make sure JVM is able to JIT Error Prone properly.
tbroyer/gradle-errorprone-plugin-v0.0.x pull request #68
Opened 2018-04-25 23:40 UTC by artem-zinnatullin

Plugin was creating new instance of `SelfFirstClassLoader` on every compilation, which resulted in class loading Error Prone classes (compiler, checks, etc) on every compilation.

That didn't give JVM a chance to reuse JITted versions of Error Prone classes.

This change alone saves about 166% of overhead added by Error Prone 2.2.0 comparing to Oracle JDK 8 `javac`.

Benchmark makes it obvious:

![benchmark](https://user-images.githubusercontent.com/967132/39278297-474ff83c-48a7-11e8-82d2-00829783e72d.png)

2018-04-25 23:52 UTC, jbduncan commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +    private static final Map<Set<URL>, SelfFirstClassLoader> CACHE = new HashMap<>(1);
I think this should be a `Set<URI>` or `Set<String>` if possible, because by my limited understanding, `HashMap` uses `Object#equals` on keys in some way, and `URL`'s `equals` method does network calls, which is a pretty bad thing for such a method to do (but which cannot be fixed due to Java backwards compatibility).

2018-04-26 00:13 UTC, artem-zinnatullin commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +    private static final Map<Set<URL>, SelfFirstClassLoader> CACHE = new HashMap<>(1);
That's a good suggestion, these URLs are paths in local fs to the jars required for Error Prone, but I'll change that to strings 👍

2018-04-26 00:13 UTC, artem-zinnatullin commented
Looking at test failures

2018-04-26 03:10 UTC, artem-zinnatullin commented
Heading home, the patch works ok when I apply it to other project after publishing to mavenLocal.

But in integration tests reusing classloader results in `ClassNotFoundError`. Looks like lookup of any of the classes from list of URIs is not working.

So far I'm unsure why that happens. Maybe you'll spot the issue

2018-04-26 14:20 UTC, jbduncan commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +    private static final Map<Set<URL>, SelfFirstClassLoader> CACHE = new HashMap<>(1);
Sounds good! :)

2018-04-27 01:30 UTC, artem-zinnatullin commented
Ok, so I've spent few more hours on that.

Picture I have after debugging the plugin in integration tests (added `gradle.properties` with debugging options):

- On first compilation pass (ie on first integration test) all Error Prone -related 
classes are loaded normally
- If subsequent compilation needs classes that were not loaded on first pass, `SelfFirstClassLoader` is unable to load them but can serve already loaded classes.

This is pretty ridiculous. I've debugged it down to `URLClassLoader` internals, debugger shows that jar lookup can't find required classes even though if I open jars manually — classes are of course there.

So… I've made a ridiculous workaround for this ridiculous problem: I load all classes from Error Prone -related jars on the first pass and then of course everything works.

I'm by no means a ClassLoader expert (or expert at anything lol), so I really hope someone else will be able to spot the problem and suggest a better fix. 
Maybe guys from Gradle could help cc @eriwen @oehme

2018-04-27 02:09 UTC, artem-zinnatullin commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +    private static final Map<Set<URL>, SelfFirstClassLoader> CACHE = new HashMap<>(1);
Used `Set<URI>` to reduce number of conversions between types

2018-05-03 14:48 UTC, oehme commented
Have you checked whether the classloader was closed? That might explain why it doesn't load new classes.

I'd like to encourage you to limit the number of loaders you cache to prevent an unbounded memory leak. Just one may actually be enough, how often does one really change the version of error prone?

2018-05-03 20:45 UTC, artem-zinnatullin commented
@oehme ohh, interesting, thanks for suggestion! I'll check with debugger if it's closed or not. Maybe something reflects on compiler's ClassLoader and closes it, other than that I don't see how could it be closed.

Regarding number of loaders, initially I've cached only one ClassLoader, but then I've figured that different modules could use different versions of ErrorProne or its dependencies. Although I also don't think that's a frequent use case.

I guess it's reasonable to refactor it to cache only one ClassLoader unless someone complaints that it's not enough 👍

2018-05-03 20:50 UTC, artem-zinnatullin commented
Oh, well, it's closed by try-with-resources in the plugin 🤦‍♂️ 🤦‍♂️ 🤦‍♂️

2018-05-03 21:48 UTC, artem-zinnatullin commented
@oehme thanks a lot for your help! I've fixed the issue and now only cache single ClassLoader

@tbroyer can you please take a look?

2018-05-03 21:50 UTC, artem-zinnatullin commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +    Set<URI> uris = errorprone.getFiles().stream().map(File::toURI).collect(Collectors.toSet());
I'd like to split it into multiple lines, but google code style reformats it into single line

2018-05-03 21:50 UTC, artem-zinnatullin commented on src/test/groovy/net/ltgt/gradle/errorprone/ErrorProneBasePluginIntegrationSpec.groovy
> +        .withArguments('--info', '--stacktrace', 'compileJava')
I can revert these if you want

2018-05-03 21:53 UTC, jbduncan commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +    Set<URI> uris = errorprone.getFiles().stream().map(File::toURI).collect(Collectors.toSet());
@artem-zinnatullin I think the recognised workaround is to write the code like this:

```java
Set<URI> uris = //
    errorprone.getFiles() //
        .stream() //
        .map(File::toURI) //
        .collect(toSet());
```

I know, it ain't perfect. :)

2018-05-03 21:57 UTC, artem-zinnatullin commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +    Set<URI> uris = errorprone.getFiles().stream().map(File::toURI).collect(Collectors.toSet());
yeah no thanks 😸, I guess I'm fine with it being single line haha

2018-05-04 07:21 UTC, oehme commented
Just one final remark: Never closing that classloader means that the underlying files will remain open for the lifetime of the daemon. This means that

- if errorprone is in the dependency cache, that cache can't be deleted on Windows (though that's a rare use case)
- if the user tries to build a local copy of errorprone they won't be able to rebuild it without stopping the daemon first

2018-05-04 07:42 UTC, artem-zinnatullin commented
If Error Prone Gradle Plugin is held by Gradle daemon, it means that there is a project(s) that needs it, right? Sounds like a good reason to hold jars to me :)

The case with local copy of Error Prone is more complicated. As a workaround, local copy of Error Prone can be deployed to mavenLocal so change in version name will invalidate path to jars thus the plugin will create new ClassLoader and let GC cleanup previous instance.

2018-05-04 07:54 UTC, oehme commented
People generally use composite builds for that in Gradle or snapshots in Maven. The path remains the same in that case, just the file changes. That wouldn't be picked up by the current approach. You'd have to hash the file contents to do it reliably.

2018-05-04 08:02 UTC, artem-zinnatullin commented
Yeah, would be great to avoid hashing to avoid performance overhead (we have a lot of modules to compile).

Do you think I can rely on comparing `File.lastModified()` instead of computing and comparing hashes?

2018-05-04 08:18 UTC, oehme commented
You could approximate with lastModified + length, that's relatively safe.

2018-05-04 08:24 UTC, artem-zinnatullin commented
Sounds reasonable, will do then.

Thanks for your help, Stefan!

2018-05-04 21:10 UTC, artem-zinnatullin commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +          jars.parallelStream()
JarIdentity does I/O to read file properties, so I decided to parallelize it

2018-05-04 21:12 UTC, artem-zinnatullin commented
Implemented ClassLoader cache invalidation based on `lastModified` and `length` as suggested by @oehme 

Note that I don't explicitly close prev instance in case of jars invalidation to not break compilation that can run in parallel, GC will take care of closing closeable resources opened by URLClassLoader.

2018-05-04 22:10 UTC, jbduncan commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +          jars.parallelStream()
I think you should strongly consider using either a bog standard `stream()` or [Gradle's Worker API](https://guides.gradle.org/using-the-worker-api/). `parallelStream()` is fraught with problems (as described somewhere in Effective Java 3rd edition - I don't have the book in front of me ATM to find the exact chapter/item :P).

I also suspect that whatever increase in performance `parallelStream()` may give could easily be stripped away if another Gradle plugin running at the same time as  gradle-errorprone-plugin also uses multiple cores, since `parallelStream()` would be competing for limited CPU cores (as opposed to coordinating CPU resources if the Worker API is used instead). However, I'm no parallelism/concurrency expert, so take this paragraph with a pinch of salt. :)

2018-05-04 22:17 UTC, jbduncan commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +          jars.parallelStream()
I also remember reading somewhere that for I/O-bound operations, `CompletableFuture` is much better, since `parallelStream()` is optimised for CPU-bound operations.

2018-05-05 06:44 UTC, oehme commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +          jars.parallelStream()
I also think this is trying to overoptimize it. Keep it simple, compilation is way more costly than this file property check.

2018-05-05 06:47 UTC, oehme commented
From my experience GC will not take care of that. If you don't close it the files will remain locked. I think using a single writer/multiple reader lock and properly closing it would be better.

2018-05-11 22:01 UTC, artem-zinnatullin commented
I've update the pr with:

- `stream()` instead of `parallelStream()`
- merge with recent changes in upstream

@oehme I still stand on not closing classloader manually for multiple reasons:

1) Oracle docs state that it'll be done by GC

>In principle, once the application clears all references to a loader object, the garbage collector and finalization mechanisms will eventually ensure that all resources (such as the JarFile objects) are released and closed.

https://docs.oracle.com/javase/7/docs/technotes/guides/net/ClassLoader.html

2) In our case `UrlClassLoader` closes `JarFile`s when you call `close()`. `JarFile` extends `ZipFile` and `ZipFile`'s `finalize()` calls `close()`

So once there are no active objects holding reference to `UrlClassLoader` GC will take care of classes, classloader and closeables opened by it.

3) Closing it manually can break compilation running in parallel similarly to what I've seen before because of `close()` call that stopped classloader from loading new classes. 

Possible scenario: module A depends on set of ErrorProne classes `x`, module B depends on set of ErrorProne classes `y`. User runs `gradle build --parallel` and because we decided to only cache one classloader, another one will be closed and that can be harmful.

@tbroyer review from you would be appreciated :)

2018-05-12 17:20 UTC, PromanSEW commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +import java.util.*;
Unneccessary import

2018-05-12 17:23 UTC, oehme commented
> Oracle docs state that it'll be done by GC

There is no guarantee that a finalizer will be called in any timely fashion, don't depend on it. Correct application logic should not rely on GC.

> Closing it manually can break compilation running in parallel similarly to what I've seen before because of close() call that stopped classloader from loading new classes.

That's why I said you could use a single-writer multiple-reader lock.

2018-05-14 20:59 UTC, artem-zinnatullin commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +import java.util.*;
It's used, I was just relying (wrongly) on `./gradlew googleJavaFormat` to deal with imports, removed the other ones :)

2018-05-14 21:05 UTC, artem-zinnatullin commented
Well, part of me agrees with you but at the same time I do think that it's over-complication in runtime with GC

Anyway, I've implemented reference counting that closes ClassLoader once we reach 0 refs

2018-05-17 20:54 UTC, artem-zinnatullin commented
Anything else I need to change? :) 

I really don't want to use yet another fork of tooling, we already have a lot…

2018-05-19 12:26 UTC, tbroyer commented
@oehme I'm wondering; couldn't we _just_ key the classloader(s) by the `rootProject` (or maybe it's not even necessary if there's a distinct classloader per root project / build) and (more importantly) register a `buildFinished` to `close()` (and release) it?

@artem-zinnatullin That wouldn't share a single classloader between builds, so you'd still pay the price to load the classes for each build, but wouldn't that be an acceptable trade-off?

Please note that this plugin will basically be obsolete in 8 months from now, when Java 8 will reach EOL, so a) I don't want to spend too much time on it (that doesn't mean no time at all however! see below) but b) I don't mind either adding some code that wouldn't be "the cleanest" way to do things.
In September, with the release of Java 11, the preferred way to use Error Prone with Gradle (that's actually already the case with Java 9 and 10, but they're not LTS releases) will be with `-Xplugin:ErrorProne` and the `-processorpath`, possibly through the `net.ltgt.errorprone-javacplugin` plugin.
Fwiw, my plan is to bring the `net.ltgt.errorprone-javacplugin` DSL to this plugin so it'll be possible to apply either plugin depending on the Java version and keep the same way of configuring Error Prone itself through the DSL. Then some time in 2019, I'll most probably deploy the `net.ltgt.errorprone-javacplugin` under the `net.ltgt.errorprone` name, then somehow _deprecate_ the other plugin ID so that `net.ltgt.errorprone` will use the `-Xplugin` way in a year or so.

2018-05-19 13:27 UTC, oehme commented
@tbroyer Closing it when the build finishes would negate a lot of the benefit. You'd loose the warmed up classes for the next build.

2018-05-22 21:37 UTC, artem-zinnatullin commented
@tbroyer that's unfortunately is not an option for us :( 

We have 529 Gradle modules in the project atm, so we need to be very careful with build performance. We actually already use fork with this patch for about 4 days on pretty parellized builds (32 threads on CI, `--parallel`), didn't notice any issues so far. 

This PR actually reduces memory consumption in parallel builds with multiple modules, so I wouldn't worry about keeping classloader in memory, that's by design.

@oehme 

>I actually want to do cross-build sharing of processor classloaders in Gradle core (probably as an opt-in).

Ohh that'd be nice!

2018-05-23 15:06 UTC, tbroyer requested changes

2018-05-23 15:06 UTC, tbroyer commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +              .map(jarUri -> new HashMap.SimpleEntry<>(jarUri, new JarIdentity(jarUri)))
Use `AbstractMap` rather than `HashMap`, as that's where `SimpleEntry` is actually defined. Also how about using `SimpleImmutableEntry` instead?

Or maybe store the `jarUri` into `JarIdentity` so that `.map()` just has to return a `JarIdentity`, and the `Collectors.toMap` could use `JarIdentity::getURI` and `Function.identity()` as arguments.

Or! Because using `Set` and `Map` don't guarantee that we keep the ordering (which **is** significant), and it'll be _too easy_ to break it in the future; how about using a `List<JarIdentity>` instead? (storing the `URI` into the `JarIdentity`) We don't actually need a `Map` as the only things we do with it are `.equals(…)` and `.keySet().stream().map(…)`. `.equals(…)` would work the same (actually better, ensuring the same order), and the `.map(…)` is easy to _map_ to a `List`.

Lastly, how about turning the `URI` into `String`? `URI#toURL()` is implemented as `new URL(toString())` already.

2018-05-23 15:06 UTC, tbroyer commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +                      AbstractMap.SimpleEntry::getKey, AbstractMap.SimpleEntry::getValue));
Use `Map.Entry::getKey` and `Map.Entry::getValue`?

2018-05-23 15:06 UTC, tbroyer commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +  static final class ErrorProneJars {
How about using AutoValue?

In any case, I'd prefer static factory methods to constructors that do I/O.

2018-05-23 15:06 UTC, tbroyer commented on src/test/groovy/net/ltgt/gradle/errorprone/ErrorProneCompilerSpec.groovy
> +        classLoader1 == classLoader2
This should probably use `.is()` to make it explicit that we want to test reference equality.

2018-05-23 15:06 UTC, tbroyer commented on src/test/groovy/net/ltgt/gradle/errorprone/ErrorProneCompilerSpec.groovy
> +
nit: remove blank line

2018-05-23 15:06 UTC, tbroyer commented on src/test/groovy/net/ltgt/gradle/errorprone/ErrorProneCompilerSpec.groovy
> +class ErrorProneCompilerSpec extends Specification {
Correct me if I'm wrong but none of these methods test the `JarIdentity` (i.e. `getInstance` returning a new classloader whenever the JARs in the classpath change in any way –lastModified or length).

2018-05-23 15:06 UTC, tbroyer commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +      registerAsParallelCapable();
:+1:

2018-05-23 15:06 UTC, tbroyer commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +        final File jar = new File(jarUri);
Instead of going from `File` to `URI` and back to `File`, how about passing the `File`s all the way down to here, convert them to `URI`s for the _cache key_, and then to `URL`s for the `URLClassLoader`?

2018-05-23 15:06 UTC, tbroyer commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +            instance.incrementRefCount(); // Indicate new static reference.
Better initialize the `AtomicInteger` with `1`.

2018-05-23 15:06 UTC, tbroyer commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +        this.lengthBytes = jar.length();
How about directories? Because this should never happen (and/or we don't really care), how about recording this fact here, and make it so that we never cache/reuse the classloader if any entry is a directory?

2018-05-23 15:06 UTC, tbroyer commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +    private static final Object LOCK = new Object();
Add appropriate Error Prone annotations everywhere: `@GuardedBy("LOCK")` on `INSTANCE`, and `@Immutable` on `ErrorProneJars` and `JarIdentity`.

2018-05-23 15:06 UTC, tbroyer commented on src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java
> +              instance.decrementRefCount(); // Indicate release of static reference.
Correct me if I'm wrong but there's a race condition here: `INSTANCE` is still `instance`, so another thread could call `getInstance()` and have that value returned; but `decremententRefCount()` could still be called before the other thread's call to `incrementRefCount()`, resulting in the other thread getting a `close()`d classloader.

This could be solved by simply moving that call to after `INSTANCE` is reassigned to the new classloader; but how about using a `ReentrantReadWriteLock` as `LOCK` instead; or simply locking unconditionally? (fwiw, `GuardedBy("LOCK")` kind of requires this, and I think it's a good thing)
Would the overhead of an unconditional lock really be that big? We don't expect much contention do we? (and in any case it'd still be way better than the current situation :wink:)

2018-08-27 12:42 UTC, emartynov commented
Interesting change but looks like Artem is already satisfied with the usage of the forked plugin. Commenting to stay tuned with all latest replies or changed here.

2018-08-27 13:24 UTC, tbroyer commented
Fwiw, I'll soon (a matter of weeks) discontinue this plugin and replace its implementation entirely with https://github.com/tbroyer/gradle-errorprone-javacplugin-plugin, as we've found a way to make it work with JDK 8 (see the README, I'll probably make it "automatic" by integrating it directly into the plugin).
That approach should also make this issue moot as far as the javac classes are concerned, and/or in the hands of the javac developers (or possibly Gradle) with regards to Error Prone classes themselves (loaded as an `-Xplugin`, so eventually using `StandardFileManager#getServiceLoader`, which itself uses `StandardFileManager#getClassLoader(ANNOTATION_PROCESSOR_PATH)` by default; this classloader could then possibly be cached).

2018-08-30 14:06 UTC, closed without merging

2018-09-02 21:26 UTC, artem-zinnatullin commented
Direction @tbroyer is evolving ErrorProne support for Gradle is good and I'm pretty happy about it, the main point of this PR was to make sure issue is known, discussed and that a workaround is showcased.

I'm sorry I didn't push the PR to completion, I'm alone in my team and just had to use fork before this PR was even created and move on onto other tasks. I'm trying to upstream most of changes I do to OSS, but we're all just a humans after all :)

2018-09-02 21:29 UTC, emartynov commented
Artem, no blame at all. We are all humans and you're doing a great job over expectations!

2018-09-02 21:33 UTC, oehme commented
You can follow https://github.com/gradle/gradle/issues/5430 for a potential solution in Gradle.